CREATE TABLE CLIENT(
	NAME VARCHAR(20)NOT NULL,
	BIRTH DATE NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(150) NOT NULL,
	PHONE INTEGER,
	TEL INTEGER,
	ID VARCHAR(20)NOT NULL,
	PASSWORD VARCHAR(20)NOT NULL,
	GETAGREE NUMBER(1,0) NOT NULL,
	PRIMARY KEY(ID)
);

SELECT * FROM TAB;
SELECT * FROM CLIENT;


ALTER TABLE CLIENT MODIFY(PHONE VARCHAR(15));
ALTER TABLE CLIENT MODIFY(TEL VARCHAR(15));
DROP TABLE CLIENT;

CREATE TABLE CLIENT(
	NAME VARCHAR(20),
	BIRTH DATE ,
	EMAIL VARCHAR(50) ,
	ADDRESS VARCHAR(150) ,
	PHONE INTEGER,
	TEL INTEGER,
	ID VARCHAR(20),
	PASSWORD VARCHAR(20),
	GETAGREE NUMBER(1,0),
	PRIMARY KEY(ID)
);

SELECT * FROM CLIENT;

CREATE TABLE CLIENT(
	NAME VARCHAR(20),
	BIRTH DATE ,
	EMAIL VARCHAR(50) ,
	ADDR VARCHAR(150) ,
	PHONE VARCHAR(15),
	TEL VARCHAR(15),
	ID VARCHAR(20)PRIMARY KEY,
	PASSWORD VARCHAR(20),
	GETAGREE NUMBER(1,0)
	IMAGE BLOB
);

DROP TABLE ADMIN;

CREATE TABLE ADMIN(
	NAME VARCHAR(20),
	BIRTH DATE,
	EMAIL VARCHAR(50) ,
	ADDR VARCHAR(150) ,
	PHONE VARCHAR(15),
	TEL VARCHAR(15),
	ID VARCHAR(20),
	PASSWORD VARCHAR(20),
	PRIMARY KEY(ID)
	);

INSERT INTO ADMIN(NAME,BIRTH,EMAIL,ADDR,PHONE VARCHAR(15),TEL VARCHAR(15),ID,PASSWORD)
VALUES('조은애','1995/09/22','dmsdo922@naver.com','경기 부천시 원미구','01025767152','0326557152','admin950922','Gosemvhs1');

SELECT * FROM ADMIN;


DELETE FROM ADMIN 
WHERE PHONE = '01021047152';


ALTER TABLE ADMIN MODIFY PHONE VARCHAR(15);
ALTER TABLE ADMIN MODIFY TEL VARCHAR(15);

SELECT * FROM CLIENT;

UPDATE ADMIN
SET TEL = '01021047152'
WHERE ID = 'admin950922';

SELECT * FROM ADMIN;
SELECT * FROM TAB;


ALTER TABLE CLIENT ADD IMAGE BLOB
ALTER TABLE ADMIN ADD IMAGE BLOB
ALTER TABLE CLIENT ADD MAIN BLOB

ALTER TABLE CLIENT MODIFY PASSWORD VARCHAR2(15);
DELETE CLIENT;
SELECT * FROM CLIENT;

DELETE FROM CLIENT WHERE PHONE = '01012348345'

ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';

ALTER TABLE CLIENT MODIFY GETAGREE VARCHAR(5);

Select * from CLIENT where name = '������'

SELECT * FROM CLIENT;

select * from clientView;
DROP TABLE ROOMCHAT
ALTER TABLE CLIENT MODIFY MAIN CLOB

CREATE TABLE EMO (
	EMO_N VARCHAR2(10),
	EMOTION BLOB
)
SELECT * FROM EMO

CREATE TABLE ROOMCHAT(
	ID VARCHAR2(15),
	NAME1 VARCHAR2(20),
	ROOM1 BLOB,
	NAME2 VARCHAR2(20),
	ROOM2 BLOB,
	NAME3 VARCHAR2(20),
	ROOM3 BLOB
	)
	
SELECT * FROM ROOMCHAT where id = 'qhfk00'

INSERT INTO ROOMCHAT(ID)
values ('dkfka00')

SELECT * FROM CLIENT
ALTER TABLE CLIENT MODIFY(PHONE VARCHAR(15))
ALTER TABLE CLIENT MODIFY(GETAGREE  NUMBER(1,0))

DROP TABLE CLIENT


CREATE TABLE CLIENT(
	NAME VARCHAR(20),
	BIRTH DATE ,
	EMAIL VARCHAR(50) ,
	ADDR VARCHAR(150) ,
	PHONE VARCHAR(15),
	TEL VARCHAR(20),
	ID VARCHAR(20),
	PASSWORD VARCHAR(20),
	GETAGREE NUMBER(1,0),
	IMAGE BLOB,
	PRIMARY KEY(ID)
);

select * from All_Tab_columns  ;

-- CLIENT / ADMIN / ROOMCHAT / EMO --

CREATE TABLE client(name VARCHAR(20), birth DATE, email VARCHAR(50), addr VARCHAR(150), phone VARCHAR(15), id VARCHAR(20) PRIMARY KEY, password VARCHAR(20), agree TINYINT, image BLOB) ENGINE=INNODB;
CREATE TABLE roomchat(
	id VARCHAR2(15),
	name1 VARCHAR2(20),
	room1 BLOB,
	name2 VARCHAR2(20),
	room2 BLOB,
	name3 VARCHAR2(20),
	room3 BLOB
	)

CREATE TABLE ADMIN(
	name VARCHAR(20),
	birth DATE,
	email VARCHAR(50) ,
	phone VARCHAR(15),
	id VARCHAR(20) primary key,
	password VARCHAR(20)
	);

INSERT INTO ADMIN
VALUES('조은애','1995/09/22','dmsdo922@naver.com', '01025767152','admin','1234');
